abbr l "ls -Fogh"
abbr la "ls -AFogh"
abbr gst "git status"
abbr gco "git checkout"
abbr gcb "git checkout -b"
abbr gb "git branch"
abbr gba "git branch -a"
abbr gaa "git add -a"
abbr gau "git add -u"
abbr gc "git commit"
abbr gcm "git commit -m"
abbr gcan "git commit --amend --no-edit"
abbr gd "git diff"
abbr gds "git diff --staged"
abbr gp "git push"
abbr ggl "git pull"
abbr gl "git log --oneline --graph --decorate"
abbr grb "git rebase"
abbr grs "git restore"
abbr gss "git stash"
abbr gsp "git stash pop"
